user:
  name: 茵符草
  first_name: c
  last_name: INFO
  email: beta-s@outlook.com
  domain: https://www.imalun.com
  avatar: /img/avatar.jpeg
  describe: describe

footer:
  powered:
    enable: false

sidebar:
  social:
    - name: github
      icon: fab fa-github
      url: https://github.com
  info:
    - key: University
      val: CQU
    - key: Loc
      val: Tianjin